Repository aws/aws-sdk-go-v2, pull requests merged in 2020-01, with the labels that each got.

#461 `aws`: Add context on credential providers, EC2Metadata client o…
  CHANGELOG_PENDING.md
  aws/chain_provider.go
  aws/chain_provider_test.go
  aws/credentials.go
  aws/credentials_bench_test.go
  aws/credentials_test.go
  aws/defaults/handlers_test.go
  aws/ec2metadata/api_client_test.go
  aws/ec2metadata/api_ops.go
  aws/ec2metadata/api_ops_test.go
  aws/ec2metadata/token_provider.go
  aws/ec2rolecreds/provider.go
  aws/ec2rolecreds/provider_test.go
  aws/endpointcreds/provider.go
  aws/endpointcreds/provider_test.go
  aws/external/config_test.go
  aws/external/example_test.go
  aws/external/provider.go
  aws/external/resolve_test.go
  aws/request_test.go
  aws/signer/v2/v2.go
  aws/signer/v2/v2_test.go
  aws/signer/v4/functional_test.go
  aws/signer/v4/v4.go
  aws/signer/v4/v4_test.go
  aws/static_provider.go
  aws/static_provider_test.go
  aws/stscreds/provider.go
  aws/stscreds/provider_test.go
  example/service/rds/rdsutils/authentication/iam_authentication.go
  example/service/sts/assumeRole/assumeRole.go
  internal/awstesting/util.go
  service/rds/rdsutils/builder.go
  service/rds/rdsutils/builder_test.go
  service/rds/rdsutils/connect.go
  service/rds/rdsutils/connect_test.go
  service/rds/rdsutils/example_test.go
Labels: work-in-progress

#471 `private/model`: Add shape name validation for structs and enums
  CHANGELOG_PENDING.md
  private/model/api/load.go
  private/model/api/passes.go
  private/model/api/passes_test.go
  service/ec2/api_enums.go
  service/iam/api_enums.go
  service/mediapackage/api_enums.go
  service/mediapackage/api_types.go
Labels: breaking-change

#417 internal/sdkio: add RingBuffer data structure to the sdk
  CHANGELOG_PENDING.md
  internal/sdkio/ringbuffer.go
  internal/sdkio/ringbuffer_test.go
Labels: ready-to-merge

#462 `aws/ec2metadata`: modifies ec2metadata client to use appropriate request timeouts
  CHANGELOG_PENDING.md
  aws/ec2metadata/api_client.go
  aws/ec2metadata/api_ops_test.go
  aws/signer/v2/v2_test.go
  aws/signer/v4/v4.go
Labels: needs-review

#474 Support for Loading Service Specific Configuration from External Sources During Client Creation
  aws/config.go
  aws/external/config.go
  aws/external/env_config.go
  aws/external/env_config_test.go
  aws/external/shared_config.go
  aws/external/shared_config_test.go
  aws/external/testdata/shared_config
  models/protocol_tests/generate.go
  private/model/api/api.go
  private/model/api/endpoint_trait.go
  private/model/api/service_specific_config.go
  private/model/api/shape.go
  private/model/api/waiters.go
  private/model/cli/gen-api/main.go
  service/s3/api_client.go
  service/s3/api_client_config.go
  service/s3/api_client_config_test.go
  service/s3/internal/external/external.go
  service/s3/internal/external/external_test.go
Labels: needs-review

#478 Simplify Service Client Configuration Resolving
  aws/config.go
  aws/external/config.go
  aws/external/config_test.go
  private/model/api/api.go
  service/s3/api_client.go
  service/s3/api_client_config.go
  service/s3/api_client_config_test.go
Labels: needs-review

#477 Add timestamp support for SDK's generated API smoke tests
  models/apis/marketplacecommerceanalytics/2015-07-01/smoke.json
  private/model/api/api.go
  private/model/api/docstring.go
  private/model/api/eventstream.go
  private/model/api/example.go
  private/model/api/example_test.go
  private/model/api/examples_builder.go
  private/model/api/load.go
  private/model/api/pagination.go
  private/model/api/shape_value_builder.go
  private/model/api/smoke.go
  private/model/api/waiters.go
  private/model/cli/gen-api/main.go
  service/applicationautoscaling/api_examples_test.go
  service/autoscaling/api_examples_test.go
  service/batch/api_examples_test.go
  service/cloud9/api_examples_test.go
  service/codebuild/api_examples_test.go
  service/costandusagereportservice/api_examples_test.go
  service/databasemigrationservice/api_examples_test.go
  service/devicefarm/api_examples_test.go
  service/dynamodb/api_examples_test.go
  service/dynamodbstreams/api_examples_test.go
  service/ec2/api_examples_test.go
  service/ec2instanceconnect/api_examples_test.go
  service/ecr/api_examples_test.go
  service/ecs/api_examples_test.go
  service/efs/api_examples_test.go
  service/eks/api_examples_test.go
  service/elasticache/api_examples_test.go
  service/elasticbeanstalk/api_examples_test.go
  service/elasticloadbalancing/api_examples_test.go
  service/elasticloadbalancingv2/api_examples_test.go
  service/fsx/api_examples_test.go
  service/glacier/api_examples_test.go
  service/iam/api_examples_test.go
  service/inspector/api_examples_test.go
  service/kms/api_examples_test.go
  service/lambda/api_examples_test.go
  service/lexmodelbuildingservice/api_examples_test.go
  service/marketplacecommerceanalytics/api_integ_test.go
  service/organizations/api_examples_test.go
  service/polly/api_examples_test.go
  service/pricing/api_examples_test.go
  service/rds/api_examples_test.go
  service/rekognition/api_examples_test.go
  service/route53/api_examples_test.go
  service/s3/api_examples_test.go
  service/secretsmanager/api_examples_test.go
  service/ses/api_examples_test.go
  service/snowball/api_examples_test.go
  service/storagegateway/api_examples_test.go
  service/sts/api_examples_test.go
  service/waf/api_examples_test.go
  service/wafregional/api_examples_test.go
Labels: needs-review
